### PR TITLE
Cleanup and fixes for osx

### PR DESCRIPTION
**Pull request by jacobrosenthal**
I actually dont know how it works at all on osx atm, but it mostly seems to. The mtu starts out as 0 so the first read is the entire buffer, then the second read is indexed in the middle and overflows?..  but I havent been able to refactor yet without breaking it entirely.  I think the mtus need some refactoring upstream anyway

```
3c68746d6c3e0a20203c686561643e0a202020203c7469746c653e46617420426561636f6e2044656d6f3c2f7469746c653e0a202020203c6d65746120636861727365743d275554462d38273e0a202020203c6d657461206e616d653d276465736372697074696f6e2720636f6e74656e743d2746617420426561636f6e2044656d6f272f3e0a20203c2f686561643e0a20203c626f64793e0a202020203c68313e48656c6c6f576f726c643c2f68313e0a202020203c73766720786d6c6e733d22687474703a2f2f7777772e77332e6f72672f323030302f737667222077696474683d2231373122206865696768743d22323032223e3c672066696c6c3d2223334638324334222066696c6c2d72756c653d226576656e6f6464223e3c7061746820643d224d3134312e322038352e3363302d33312d32352d35362d35362d35362d33302e3720302d35352e382032352d35352e38203536203020313720372e382033322e352032302034322e386c31302d3130632d392e382d372e362d31362d31392e342d31362d33322e3720302d32332e322031382e382d34322034322d343220323320302034312e382031382e382034312e3820343220302031332e332d362e322032352d31362033322e386c31302031306331322e322d31302e322032302d32352e362032302d34322e37222f3e3c7061746820643d224d31342038352e334331342034362034362031342038352e332031347337312e332033322037312e332037312e3363302032312e342d392e352034302e362d32342e352035332e376c31302031306331372e362d31352e372032382e362d33382e342032382e362d36332e3720302d34372d33382e322d38352e332d38352e332d38352e334333382e33203020302033382e3220302038352e3363302032352e332031312034382032382e352036332e366c31302d31304332332e3520313236203134203130362e372031342038352e33222f3e3c7061746820643d224d38392e32203230302e33632d3220322d352e3520322d372e3620306c2d33352e382d33352e38632d322d322d322d352e3520302d372e366c33352e382d333663322d3220352e352d3220372e3620306c33352e3820333663322032203220352e34203020372e356c2d33352e382033352e387a222f3e3c2f673e3c2f7376673e0a20203c2f626f64793e200a3c2f
on -> mtuChange: 505
on -> mtuChange: 505

37222f3e3c7061746820643d224d31342038352e334331342034362034362031342038352e332031347337312e332033322037312e332037312e3363302032312e342d392e352034302e362d32342e352035332e376c31302031306331372e362d31352e372032382e362d33382e342032382e362d36332e3720302d34372d33382e322d38352e332d38352e332d38352e334333382e33203020302033382e3220302038352e3363302032352e332031312034382032382e352036332e366c31302d31304332332e3520313236203134203130362e372031342038352e33222f3e3c7061746820643d224d38392e32203230302e33632d3220322d352e3520322d372e3620306c2d33352e382d33352e38632d322d322d322d352e3520302d372e366c33352e382d333663322d3220352e352d3220372e3620306c33352e3820333663322032203220352e34203020372e356c2d33352e382033352e387a222f3e3c2f673e3c2f7376673e0a20203c2f626f64793e200a3c2f68746d6c3e
```

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Oh, also the big change for you is not using accept, as that does come in on osx, but with the mtu oddness, it resets the index in the middle of sending. Does a reset on disconnect work for linux?

**Comment by hardillb** [comment]
There is something not quite working with this for me, it's not delivering all the payload (it's cutting the last 5 chars off the end "html>")

**Comment by hardillb** [comment]
The bleno.on('mtuChange') is never getting called in this new version so initial transfer size is being set to -5

**Comment by jacobrosenthal** [comment]
Ive seen that occasionally myself. I THINK thats in the original code, not
this, as youll notice I havent actually touched the loop at all to my
knowledge

**Comment by hardillb** [comment]
But you have moved the setting up of the _mtuChange_ callback, I've never seen it not get called when it was global

**Comment by hardillb** [comment]
Odd, this might be a bleno thing, I've got 2 separate trees which behave differently the only difference looks to be the bleno level, with the latest version the on `mtuChanged` is never called and `bleno.mtu` always is 20

The working version if 0.1.14, the new 0.4.0 isn't and doesn't list 'mtuChange' as a event in the doc.

I have no idea how I ended up 0.1.14 in the version I've been working with as it should have come fro a straight `npm install` in the root of the project

Sounds like something for @sandeepmistry

**Comment by sandeepmistry** [comment]
@hardillb's I've pushed a fix for the MTU event on Linux: https://github.com/sandeepmistry/bleno/commit/72ecd3a82bbe1d09fe976e2124920967fc12a8f9

You can try it out with `npm install sandeepmistry/bleno` until a new release is published to npm.

**Comment by hardillb** [comment]
@sandeepmistry The mtu change is showing up but now I'm not getting the `onReadRequest()` getting called

**Comment by sandeepmistry** [comment]
@hardillb I did some basic testing with [test.js](https://github.com/sandeepmistry/bleno/blob/master/test.js) from bleno, everything appears to be functional.

Please open a Github issue on bleno with more details (debug logs, HCI dump capture, etc).

**Comment by hardillb** [comment]
@sandeepmistry having got into the office and tried again on the standard rPi (usb ble device) it seams to be working properly now. It might be a problem with the rPi Zero and RedBear IoT pHat I was using over the weekend.

Anyway, I'm going to merge @jacobrosenthal's changes now as they seam to work. Let me know when the new version of the bleno is on npm and I'll bump the package.json

**Pull request merged**
